[package]
name = "linux_wasm_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.3", features = ["derive"] }
rand = "0.8.5"
vm-fdt = "0.3.0"
wasmtime = "21"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
