on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build . --print-build-logs
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result/

      - run: rm -f tools/wasm/vmlinux.wasm && cp result/vmlinux.wasm tools/wasm/
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: tools/wasm/
          
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/wasm'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4